import Head from 'next/head';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import FunFact from '../components/FunFact';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import TeamSlider from '../components/Slider/TeamSlider';
import Spacing from '../components/Spacing';
import Accordion from '../components/Accordion';
import { Icon } from '@iconify/react';
import Button from '../components/Button';


export default function About() {
  const funfaceData = [
    {
      title: 'Projects',
      factNumber: '5K',
    },
    {
      title: 'No of states we delive',
      factNumber: '15',
    },
    {
      title: 'No of Orders',
      factNumber: '100K+',
    },
    {
      title: 'Number of Deliveries',
      factNumber: '100K+',
    },
  ];
  return (
    <>
      <Head>
        <title>Home - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Page Heading Section */}
        <PageHeading
          title="About ThunderX Premium"
          bgSrc="images/about_hero_bg.jpeg"
          pageLinkText="About Us"
        />
        {/* End Page Heading Section */}

        {/* Start About Section */}
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-6 col-lg-7">
              <SectionHeading
                title="Thunderx Premium"
                subtitle="About"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                Established in the year 2011, ThunderX Laminates is the leading Manufacturer Trader of HPL Sheet – High pressure Laminate Sheets and much more. These products are enormously employed in the market owing to their longer working life, low maintenance, top performance and nominal prices. Being a quality conscious entity, our solitary objective is to supply the only best quality products to our clients. ThunderX Laminates are ideal for all kinds of interior and exterior applications, including furniture making, home interiors ,exterior application ,offices, hotels & resorts, malls & retail stores,hospitals,educational institutions and industrial establishments. Our products can also be used for flooring systems and wall cladding solutions. Whatever your design preferences are, you’ll get the perfect finish with ThunderX Laminates. Our strength is our employees’ dedication to teamwork, commitment to excellence, and focus on continuous improvement. Our interactions are based on transparency and mutual respect. Integrity, credibility, reliability and consistency define everything we do. “We will not promise more than we can deliver—we will deliver more than we promise.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
            </Div>
            <Div className="col-lg-5 offset-xl-1">
              <img
                src="/images/post.webp"
                alt="About"
                className="w-100 cs-radius_15"
              />
              <Spacing lg="25" md="25" />
            </Div>
            <Div className="col-lg-7">
            <SectionHeading
                title="We’re a team of problem solvers"
                subtitle=""
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                Our team is made up of passionate people who are committed to helping our customers solve their problems. We believe that the best way to do this is through communication and collaboration, so we work hard to make sure that all of our interactions are meaningful and productive. We know that your time is valuable, so we only take on projects that are both challenging and rewarding. We don’t want you to feel like you’re just another number on our list–we want you to feel like someone who matters, because we know how important your success is for us as well! ThunderX Laminates
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
 
              <Spacing lg="25" md="25" />
            </Div>
            <Div className="col-lg-5">
            <SectionHeading
                title="Our Goal"
                subtitle=""
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                Thunder X Premium Laminate isn't just a company that manufactures HPL sheets; it's a testament to the power of innovation, quality, and commitment. With our sheets, you're not just adorning spaces; you're investing in the enduring elegance, resilience, and satisfaction that define Thunder X. Welcome to a world where style meets substance, and where your vision finds its true expression our commitment transcends the mere manufacturing of exceptional products. We take immense pride in our holistic approach to customer satisfaction. Our unwavering dedication to delivering not only top-notch products but also unparalleled customer service has become a cornerstone of our identity.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
              <Spacing lg="25" md="25" />
            </Div>
          </Div>
        </Div>
        <Spacing lg="75" md="55" />
        {/* End About Section */}

        {/* Start Fun Fact Section */}
        <Div className="container">
          <FunFact
            title="Our Vision"
            subtitle="The vision for HPL (High-Pressure Laminate) sheets involves becoming a leading choice for durable and stylish surfacing materials in both residential and commercial spaces. This includes a commitment to continuous innovation, offering a wide range of designs and textures, and providing solutions that cater to diverse customer needs"
            data={funfaceData}
          />
        </Div>
        {/* End Fun Fact Section */}

        {/* Start Why Choose Section */}
        <Spacing lg="100" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-image_layer cs-style1">
                <Div className="cs-image_layer_in">
                  <img
                    src="/images/team.webp"
                    alt="About"
                    className="w-100 cs-radius_15"
                  />
                </Div>
              </Div>
              <Spacing lg="0" md="40" />
            </Div>
            <Div className="col-xl-5 offset-xl-1 col-lg-6">
              <SectionHeading
                title=" ThunderX laminates comprises our stellar contributors."
                subtitle="The team powering"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                1. More than 50+ years of experience.
                </p>
                <Spacing lg="15" md="15" />
                <p className="cs-m0">
                2. 100% quality, UV-resistant, termite-proof,and fire-retardant,ThunderX Premium ensures longevity and safety.Its captivating textures,graffiti resistance,and eco-friendliness redefine excellence.
                </p>
                <Spacing lg="30" md="30" />
                <p className="cs-m0">
                3. Resistant to solvents and scratches,it maintains its allure.
                </p>
                <Spacing lg="30" md="30" />
                <p>
                4. Obtained the international quality Test Certifications ISO 9001, CE , GMP, IndiaMart Trusted Seal.
                </p>
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="0" />
              </SectionHeading>
            </Div>
          </Div>
        </Div>
        {/* End Why Choose Section */}

        {/* Start Team Section */}
        <Spacing lg="145" md="80" />
        <Div className="container">
          <SectionHeading
            title="Stars In ThunderX<br/>"
            subtitle="Digital Appearance Of Bollywood"
            variant="cs-style1"
          />
          <Spacing lg="85" md="45" />
          <TeamSlider />
        </Div>
        {/* End Team Section */}
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-lg-4">
              <Div className="cs-faq_nav cs-radius_15">
                <h2 className="cs-faq_nav_title cs-m0">FAQ Category</h2>
                <Div className="cs-height_30 cs-height_lg_30" />
                <ul className="cs-list cs-style1 cs-mp0">
                  <li>
                    <Button
                      variant="cs-type2"
                      btnLink="#"
                      btnText="Service related"
                      icon={
                        <Icon icon="material-symbols:content-copy-outline-rounded" />
                      }
                    />
                  </li>
                  <li>
                    <Button
                      variant="cs-type2"
                      btnLink="#"
                      btnText="Pricing"
                      icon={
                        <Icon icon="material-symbols:content-copy-outline-rounded" />
                      }
                    />
                  </li>
                  <li>
                    <Button
                      variant="cs-type2"
                      btnLink="#"
                      btnText="Project delivery"
                      icon={
                        <Icon icon="material-symbols:content-copy-outline-rounded" />
                      }
                    />
                  </li>
                  <li>
                    <Button
                      variant="cs-type2"
                      btnLink="#"
                      btnText="Documentation"
                      icon={
                        <Icon icon="material-symbols:content-copy-outline-rounded" />
                      }
                    />
                  </li>
                </ul>
              </Div>
            </Div>
            <Div className="col-lg-7 offset-lg-1">
              <Spacing lg="0" md="40" />
              <Accordion />
            </Div>
          </Div>
        </Div>

        {/* Start CTA Section */}
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Cta
            title="Let’s disscuse make y <br />your space<i>awesome</i> together"
            btnText="Let's have a Meeting together"
            btnLink="https://wa.me/918989944488"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
        {/* End CTA Section */}
        
        
        
      </Layout>
    </>
  );
}
