import Head from 'next/head';
import Card from '../components/Card';
import Cta from '../components/Cta';
import Div from '../components/Div';
import FunFact from '../components/FunFact';
import Hero from '../components/Hero';
import Layout from '../components/Layout';
import LogoList from '../components/LogoList';
import MovingText from '../components/MovingText';
import SectionHeading from '../components/SectionHeading';
import PortfolioSlider from '../components/Slider/PortfolioSlider';
import PostSlider from '../components/Slider/PostSlider';
import TeamSlider from '../components/Slider/TeamSlider';
import TestimonialSlider from '../components/Slider/TestimonialSlider';
import TimelineSlider from '../components/Slider/TimelineSlider';
import Spacing from '../components/Spacing';
import VideoModal from '../components/VideoModal';

export default function Home() {
  // Hero Social Links
  const heroSocialLinks = [
    {
      name: 'Instagram',
      links: 'https://www.instagram.com/thunderx_laminates/',
    },
    {
      name: 'Facebook',
      links: 'https://www.facebook.com/thunderxlaminates/',
    },
  ];

  // FunFact Data
  const funfaceData = [
    {
      title: 'Projects',
      factNumber: '5K',
    },
    {
      title: 'No of states we deliver',
      factNumber: '15',
    },
    {
      title: 'No of Orders',
      factNumber: '100K+',
    },
    {
      title: 'Number of Deliveries',
      factNumber: '100K+',
    },
  ];

  return (
    <>
      <Head>
        <title>ThunderX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Hero Section */}
        <Hero
          title="Where Durability <br/>Meets Excellence!"
          subtitle="Experience Unrivaled Strength and Style with ThunderX Premium Laminates!"
          btnText="Get a Quote"
          btnLink="https://wa.me/918989944488"
          scrollDownId="#FunFact"
          socialLinksHeading="Follow Us"
          heroSocialLinks={heroSocialLinks}
          bgImageUrl="/images/background.webp"
        />
        {/* End Hero Section */}

        {/* Start FunFact Section */}
        <div id="FunFact"className="container">
          <FunFact
            variant="cs-type1"
            title="Our Mission"
            subtitle="Our mission at HPL (High-Pressure Laminate) sheets is to deliver resilient, decorative, and adaptable surfacing solutions. From furniture to countertops and walls, we provide a blend of aesthetics, strength, wear resistance, and moisture protection. Our goal is to offer versatile options for both interior and exterior applications.."
            data={funfaceData}
          />
        </div>
        {/* End FunFact Section */}

        {/* Start Services Section */}
        <Spacing lg="150" md="80" />
        <Div>
          <Div className="container">
            <Div className="row">
              <Div className="col-xl-4">
                <SectionHeading
                  title=" HPL Sheets in Various Applications"
                  subtitle="Exploring the Versatility of"
                  btnText="See What We Offer"
                  btnLink="https://www.indiamart.com/shreebalajiexterio/"
                />
                <Spacing lg="90" md="45" />
              </Div>
              <Div className="col-xl-8">
                <Div className="row">
                  <Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
                  <Div className="col-lg-3 col-sm-6">
                    <Card
                      title=" Residential spaces"
                      link="https://www.indiamart.com/shreebalajiexterio/"
                      src="/images/bgm.jpg"
                      alt="Service"
                    />
                    <Spacing lg="0" md="30" />
                  </Div>
                  <Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
                  <Div className="col-lg-3 col-sm-6">
                    <Card
                      title="Educational institutions"
                      link="https://www.indiamart.com/shreebalajiexterio/"
                      src="/images/bgm.jpg"
                      alt="Service"
                    />
                    <Spacing lg="0" md="30" />
                  </Div>
                  <Div className="col-lg-3 col-sm-6">
                    <Card
                      title="Commercial spaces"
                      link="https://www.indiamart.com/shreebalajiexterio/"
                      src="/images/bgm.jpg"
                      alt="Service"
                    />
                    <Spacing lg="0" md="30" />
                  </Div>
                  <Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
                  <Div className="col-lg-3 col-sm-6">
                    <Card
                      title=" Exterior cladding"
                      link="https://www.indiamart.com/shreebalajiexterio/"
                      src="/images/bgm.jpg"
                      alt="Service"
                    />
                    <Spacing lg="0" md="30" />
                  </Div>
                  <Div className="col-lg-3 col-sm-6 cs-hidden_mobile"></Div>
                </Div>
              </Div>
            </Div>
          </Div>
        </Div>
        {/* End Services Section */}
        <Spacing lg="200" md="100" />
        <Div class="container">
          <div  class="cs-flow_wrap cs-type1">
            <h3>
            What is ThunderX Premium
            </h3>
          <p>
          Thunderx Premium Laminates,are a high-end line of laminate materials known for their superior quality and luxurious appearance. These laminates often feature more intricate designs,textures,and finishes,making them a popular choice for upscale interior projects. They are known for their durability,resistance to wear,and enhanced visual appeal.HPL premium sheets are an excellent choice for enhancing the beauty of the exterior areas of a house.These sheets are designed to offer a combination of aesthetics,durability,and low maintenance.They come in a wide range of colors,textures,and patterns,allowing you to choose a design that complements your home's architecture.
          </p>

          </div>
          
        </Div>

        {/* Start Portfolio Section */}
        <Spacing lg="150" md="50" />
        <Div>
          <Div className="container">
            <SectionHeading
              title="Portfolio to explore"
              subtitle=""
              variant="cs-style1 text-center"
            />
            <Spacing lg="90" md="45" />
          </Div>
          <PortfolioSlider />
        </Div>
        {/* End Portfolio Section */}
        

        {/* Start Awards Section */}
        <Spacing lg="150" md="80" />
        <Div className="cs-shape_wrap_2">
          <Div className="cs-shape_2">
            <Div />
          </Div>
          <Div className="container">
            <Div className="row">
              <Div className="col-xl-4">
                <SectionHeading
                  title=" ThunderX Premium"
                  subtitle="Key Features of"
                  variant="cs-style1"
                />
                <Spacing lg="90" md="45" />
              </Div>
              <Div className="col-xl-7 offset-xl-1">
                <TimelineSlider />
              </Div>
            </Div>
          </Div>
        </Div>
        {/* End Awards Section */}

        {/* Start Video Block Section */}
        <Spacing lg="130" md="70" />
        <Div className="container">
          <h2 className="cs-font_50 cs-m0 text-center cs-line_height_4">

            Thunderx Laminates are top-tier materials prized for their superior quality and luxurious look. 
          </h2>
          <Spacing lg="70" md="70" />
          <VideoModal
            videoSrc="https://www.youtube.com/watch?v=ryN5YpCfgyE"
            bgUrl="/images/youtube.webp"
          />
        </Div>
        {/* End Video Block Section */}
    

        {/* Start Team Section */}
        <Spacing lg="145" md="80" />
        <Div className="container">
          <SectionHeading
            title="Awesome team <br/>members"
            subtitle="Our Team"
            variant="cs-style1"
          />
          <Spacing lg="85" md="45" />
          <TeamSlider />
        </Div>
        <Spacing lg="150" md="80" />
        {/* End Team Section */}

        {/* Start Testimonial Section */}
        <TestimonialSlider />
        {/* End Testimonial Section */}

        {/* Start Blog Section */}
        <Spacing lg="150" md="80" />
        <Div className="cs-shape_wrap_4">
          <Div className="cs-shape_4"></Div>
          <Div className="cs-shape_4"></Div>
          <Div className="container">
            <Div className="row">
              <Div className="col-xl-4">
                <SectionHeading
                  title="Explore recent publication"
                  subtitle="Our Blog"
                  btnText="View More Blog"
                  btnLink="/blog"
                />
                <Spacing lg="90" md="45" />
              </Div>
              <Div className="col-xl-7 offset-xl-1">
                <Div className="cs-half_of_full_width">
                  <PostSlider />
                </Div>
              </Div>
            </Div>
          </Div>
        </Div>
        {/* End Blog Section */}

        {/* Start MovingText Section */}
        <Spacing lg="125" md="70" />
        <MovingText text="Our  Certifications - Our Certifications - Our Certifications -" />
        <Spacing lg="105" md="70" />
        {/* End MovingText Section */}

        {/* Start LogoList Section */}
        <Div className="container">
          <LogoList />
        </Div>
        <Spacing lg="150" md="80" />
        {/* End LogoList Section */}

        {/* Start CTA Section */}
        <Div className="container">
          <Cta
            title="Let’s disscuse make <br />your space  <i>awesome</i> together"
            btnText="Let's have a Meeting together"
            btnLink="https://wa.me/918989944488"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
