import { useRouter } from 'next/router';
import React from 'react';
import Accordion from '../components/Accordion';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';
import Head from 'next/head';


export default function ServiceDetails() {
  const router = useRouter();
  return (
    <>
       <Head>
        <title>ThunderX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Know More About HPL"
          bgSrc="/images/service_hero_bg.jpeg"
        />
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row align-items-center">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-radius_15 cs-shine_hover_1">
                <img
                  src="/images/blog1.webp"
                  alt="Member"
                  className="w-100"
                />
              </Div>
            </Div>
            <Div className="col-lg-6 offset-xl-1">
              <Spacing lg="0" md="45" />
              <Div className="cs-section_heading cs-style1">
                <h2 className="cs-section_title">History of the HPL Sheet</h2>
                <Div className="cs-height_10 cs-height_lg_10" />
                <Div className="cs-height_5 cs-height_lg_5" />
                <Div className="cs-separator cs-accent_bg" />
                <Div className="cs-height_45 cs-height_lg_25" />
                <p className="cs-m0">
                High-Pressure Laminate (HPL) sheets were developed in the early 20th century as a versatile surfacing material. They gained popularity in the 1950s due to their durability, resistance to wear, and wide range of decorative options. Originally used for electrical insulation, HPL sheets found their way into interior design and furniture due to advancements in manufacturing technology. The sheets consist of layers of paper soaked in resin, compressed under high heat and pressure. This process creates a rigid, durable sheet that's used for countertops, tabletops, wall panels, and more. Over the years, HPL sheets have evolved in terms of design, texture, and application techniques, becoming a staple in modern architecture and interior design.
                </p>
                <Div className="cs-height_45 cs-height_lg_30" />
              </Div>
            </Div>
          </Div>
        </Div>
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row align-items-center">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-radius_15 cs-shine_hover_1">
                <img
                  src="/images/blog2.webp"
                  alt="Member"
                  className="w-100"
                />
              </Div>
            </Div>
            <Div className="col-lg-6 offset-xl-1">
              <Spacing lg="0" md="45" />
              <Div className="cs-section_heading cs-style1">
                <h2 className="cs-section_title">Enhancing Exteriors with HPL Sheets</h2>
                <Div className="cs-height_10 cs-height_lg_10" />
                <Div className="cs-height_5 cs-height_lg_5" />
                <Div className="cs-separator cs-accent_bg" />
                <Div className="cs-height_45 cs-height_lg_25" />

                <p className="cs-m0">
                1. Visual Appeal :- 
                HPL sheets come in various designs, adding aesthetics to building facades.
                </p>
                <p className="cs-m0">
                2. Weather Resistance :-
                They withstand harsh elements, maintaining appearance over time.
                </p>
                <p className="cs-m0">
                3. Durability :- 
                Resistant to scratches and impacts, suitable for high-traffic areas.
                </p>
                <p className="cs-m0">
                4. Low Maintenance :-
                Easy to clean and require minimal upkeep.
                </p>
                <p className="cs-m0">
                5. UV Resistance :-
                Colors and patterns remain vibrant despite sunlight exposure.
                </p>
                <p className="cs-m0">6. Sustainability :-
                Eco-friendly options available, contributing to green building practices.
                </p>
                
              </Div>
            </Div>
          </Div>
        </Div>
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row align-items-center">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-radius_15 cs-shine_hover_1">
                <img
                  src="/images/blog3.webp"
                  alt="Member"
                  className="w-100"
                />
              </Div>
            </Div>
            <Div className="col-lg-6 offset-xl-1">
              <Spacing lg="0" md="45" />
              <Div className="cs-section_heading cs-style1">
                <h2 className="cs-section_title">"Tomorrow's Design Today: HPL Sheets' Modern Wonders"</h2>
                <Div className="cs-height_10 cs-height_lg_10" />
                <Div className="cs-height_5 cs-height_lg_5" />
                <Div className="cs-separator cs-accent_bg" />
                <Div className="cs-height_45 cs-height_lg_25" />
                <p className="cs-m0">
                1. Contemporary Flair: HPL sheets offer futuristic colors, textures, and designs, shaping tomorrow's aesthetics.
                </p>
                <p className="cs-m0">
                2. Sustainable Edge: Eco-friendly options align with future's focus on responsible materials and manufacturing.
                </p>
                <p className="cs-m0">
                3. Sustainable Edge: Eco-friendly options align with future's focus on responsible materials and manufacturing.
                </p>
                <p className="cs-m0">
                4. Enduring Excellence: Resilient against wear, weather, and time, HPL maintains brilliance for generations.
                </p>
                <p className="cs-m0">
                5. Material of Tomorrow: HPL sheets redefine construction, inspiring progress in modern design
                </p>
                <Div className="cs-height_45 cs-height_lg_30" />
              </Div>
            </Div>
          </Div>
        </Div>
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row align-items-center">
            <Div className="col-xl-5 col-lg-6">
              <Div className="cs-radius_15 cs-shine_hover_1">
                <img
                  src="/images/blog4.webp"
                  alt="Member"
                  className="w-100"
                />
              </Div>
            </Div>
            <Div className="col-lg-6 offset-xl-1">
              <Spacing lg="0" md="45" />
              <Div className="cs-section_heading cs-style1">
                <h2 className="cs-section_title">Benefits of HPL sheets:t</h2>
                <Div className="cs-height_10 cs-height_lg_10" />
                <Div className="cs-height_5 cs-height_lg_5" />
                <Div className="cs-separator cs-accent_bg" />
                <Div className="cs-height_45 cs-height_lg_25" />
                <p className="cs-m0">
                1. Durable against wear and impacts.
                </p>
                <p className="cs-m0">
                2. Resistant to moisture, stains, and chemicals.
                </p>
                <p className="cs-m0">
                3. Offers diverse colors and textures.
                </p>
                <p className="cs-m0">
                4. Easy to clean and maintain.
                </p>
                <p className="cs-m0">
                5. Suitable for hygiene-sensitive areas.
                </p>
                <p className="cs-m0">
               6. Versatile for interior and exterior use
                </p>
                <p className="cs-m0">
              7. Environmentally friendly options available.
                </p>
                <p className="cs-m0">
               8. Customizable and easy to shape.
                </p>
                <p className="cs-m0">
                9. Can resist UV damage and fire.
                </p>
                <p className="cs-m0">
                10. Consistent quality and appearance.
                </p>
                <Div className="cs-height_45 cs-height_lg_30" />
              </Div>
            </Div>
          </Div>
        </Div>
        <Spacing lg="150" md="80" />
       

        <Div className="container cs-shape_wrap_4">
          <Div className="cs-shape_4"></Div>
          <Div className="cs-shape_4"></Div>
          <Div className="container">
            <Div className="row">
              <Div className="col-xl-5 col-lg-6">
                <SectionHeading title="Some frequently asked questions and answers" subtitle="FAQ’s" />
                <Spacing lg="90" md="45" />
              </Div>
              <Div className="col-lg-6 offset-xl-1">
                <Accordion />
              </Div>
            </Div>
          </Div>
        </Div>

        <Spacing lg="150" md="80" />
        <Div className="container">
          <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Let's have a Meeting together"
            btnLink="https://wa.me/918989944488"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
      </Layout>
    </>
  );
}
